tasks:
  - init: pip install -r requirements.txt

vscode:
  extensions:
    - ms-python.python
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - ms-python.debugpy
    - ms-toolsai.vscode-jupyter-slideshow
    - ms-toolsai.vscode-jupyter-cell-tags

ports:
  - port: 9000-9100
    onOpen: ignore